Fixed student import bug, added 'Abishek V Ashok' to student section.
fossasia/gci16.fossasia.org pull request #103
Opened 2016-12-02 15:51 UTC by Abhi2424shek

Some student messed up with the code of the index.html, I now fixed it
and replaced it with jekyll code, now jekyll will import one by one by
one block of student from student.yml file just like it is done for
mentors secton and blog section.

then as part of my task here:
https://codein.withgoogle.com/dashboard/task-instances/5169781940420608/

I added my info to it

Thank you, happy coding!

2016-12-02 16:10 UTC, Abhi2424shek commented
Ok @jig08 take a look madam. It looks fine but has conflicts let me see how to resolve them.

2016-12-02 16:13 UTC, Abhi2424shek commented
@jig08 after running the commands in the checkout via cmd line, I am getting Everything is up to date but nothing is working out help please...

2016-12-02 16:21 UTC, Princu7 commented
@Abhi2424shek Did you pull new changes from the main repository yet? If not, then please run
git remote add origin https://github.com/fossasia/gci16.fossasia.org.git
git pull origin gh-pages.
Then try making a pull request.
Also this is the video for removing the merge conflicts
https://www.youtube.com/watch?v=g8BRcB9NLp4

2016-12-02 16:24 UTC, Abhi2424shek commented
@Princu7 should i close the PR and start a new one, running the code gives: Invalid refspec: gh-pages

2016-12-02 16:30 UTC, Princu7 commented
@Abhi2424shek Maybe try directly running the command `git pull`. Closing PR and reforking the repo again might do the job but it is not a good practice to follow.

2016-12-02 16:39 UTC, Abhi2424shek commented
@Princu7 let me try out

2016-12-02 16:58 UTC, Abhi2424shek commented
I have squashed all the commits into a single commit so please merge it, the squashed commit is named "Solved as stated" so please help out and approve my task. I've done pretty more with this PR...

2016-12-02 17:19 UTC, Abhi2424shek commented
@jig08 @Princu7 now I have done everything I could, now it's up to you to squash all the commits and merge (via merge pull request or simply merge the pull request). Please do so before conflicts arise as I have modified huge amount of core files. I've also submitted the task for review. Thank you...

2016-12-02 18:18 UTC, Princu7 commented
@Abhi2424shek Please post a link to your gh-pages for easy reviewing. Thanks!!

2016-12-03 02:57 UTC, Abhi2424shek commented
@Princu7 there are some conflicts let me resolve them, squash and I will send the current and my development gh-pages screen shots for easy reviewing

2016-12-03 04:22 UTC, Abhi2424shek commented
@Princu7 @jig08 @mariobehling , now is the time go ahead and merge it...
Here is the preview: [](https://abhi2424shek.github.io/gci16.fossasia.org/)
See the students section, please.

Thanks, happy coding

2016-12-03 04:23 UTC, Abhi2424shek commented
Help out quickly guys, before more conflicts arise as i have modified the core files...

2016-12-03 04:29 UTC, Abhi2424shek commented
@hemantjadon can you help out sir...

2016-12-03 04:32 UTC, hemantjadon commented
@Abhi2424shek 
Hi you will have to squash the commits before we can proceed forward and merge.
For resources on squashing the commits please check the slack channel "#gci" and see the pinned messages.

2016-12-03 04:52 UTC, Abhi2424shek commented
@hemantjadon can you send me the link

2016-12-03 04:53 UTC, Princu7 commented
@Abhi2424shek Sorry, I was busy. Here is the link
https://fossasia.slack.com/messages/gci/

2016-12-03 05:07 UTC, Abhi2424shek commented
Hey @hemantjadon @Princu7 after running git rebase -i I am getting commits that I have'nt made !

2016-12-03 05:24 UTC, Abhi2424shek commented
I squashed @hemantjude @Princu7

2016-12-03 05:35 UTC, daminisatya requested changes
No you dint squash yet!

2016-12-03 05:38 UTC, Abhi2424shek commented
I cant squash  more as it will leave conflicts again and again @daminisatya

2016-12-03 05:38 UTC, daminisatya commented
@Abhi2424shek You need to squash the top two commits. Follow the steps
```git rebase -i HEAD~2``` Which means you are taking the first two from the stack. 

Now a commad promt shows the two commit messages, select the second one as squash and first one as pick. Read the instructions on that screen clearly, then another screen pops out giving you an option to make a commit description. and then you need to force push.

```git push -f origin gh-pages``` or what ever branch you are working on.

2016-12-03 05:40 UTC, Abhi2424shek commented
@daminisatya this is what I see:
`pick cce357d Fixed studetn import bug, added abishek v ashok to student section.
pick 1ede1a9 not sure how to link, so I'm uploading a 2nd version
pick 5e5edc8 Added 2 mentors
pick a0ce48c Updated travis.yml
pick bf32256 Travis-CI: Allow building any branch name
pick 915ed68 Fix linting errors
pick c620aa0 Update students.yml
pick 3a3e8d5 Improved contributors section
pick 2cf19db Fixed inconsistencies
pick 4634aed Add student creds to html students section`

2016-12-03 05:40 UTC, daminisatya commented
Give a screenshot. It's convoluted.

2016-12-03 05:42 UTC, daminisatya commented
Also share me the screenshot after typing this

```git log```

2016-12-03 05:45 UTC, Abhi2424shek commented
@daminisatya I am seeing more than 2 commits!

2016-12-03 05:46 UTC, Abhi2424shek commented
![image](https://cloud.githubusercontent.com/assets/8947010/20857176/d8c26596-b949-11e6-8f3f-ef67effc0d04.png)

@daministaya

2016-12-03 05:49 UTC, Abhi2424shek commented
when I run
`
git rebase -i

and in the notepad type in:
pick myfirstcommit has
squash mysecond commit has
`
I am getting some cherry empty errors!

2016-12-03 05:50 UTC, daminisatya commented
```git rebase -i HEAD~2``` This is the command for your log

2016-12-03 05:52 UTC, Abhi2424shek commented
cant you squash them in the github merge pull request @daminisatya

2016-12-03 05:53 UTC, Abhi2424shek commented
@daminisatya heres what I get
![image](https://cloud.githubusercontent.com/assets/8947010/20857219/e131bb22-b94a-11e6-8e40-ff916e02a871.png)

2016-12-03 06:21 UTC, Abhi2424shek commented
@hemantjadon could you take a look

2016-12-03 06:42 UTC, hemantjadon commented
@Abhi2424shek 

* The merge button merges the repo, and does't give us opportunity to squash.

* You can simply squash the top two commits into then we can proceed merging, as @daminisatya has mentioned.

2016-12-03 06:46 UTC, Abhi2424shek commented
@hemantjadon see the down button near, it has the option i guess

2016-12-03 07:05 UTC, hemantjadon commented
@daminisatya It looks good from my side (despite of two blank commits) which can be solved using squashing while merging. Your inputs and review please ?

2016-12-03 07:07 UTC, Abhi2424shek commented
@hemantjadon should i stop trying to squash

2016-12-03 07:12 UTC, Abhi2424shek commented
@hemantjadon @Princu7 @jig08 @daminisatya , can someone now squash and merge out, so that I could work on the next task in GCI... and unleash my contributiions :)

2016-12-03 07:39 UTC, Abhi2424shek commented
Some one help out...

2016-12-03 08:04 UTC, Abhi2424shek commented
@hemantjadon i could wait

2016-12-03 08:08 UTC, Princu7 commented
@Abhi2424shek Thanks for your patience and understanding. I know it's exhausting and frustrating to wait but there are many things that have to be kept in mind before merging.

Also, If you have a problem that you can't work on other tasks without getting the current task approved since you have made changes in the master branch, then you can alter your workflow a little. From next time, you can make a separate branch for every new task you are going to do. Then you can push that branch to your forked repository and generate pull requests from there. That way, you can work on more than one task at the same time and delete the branches after the tasks are approved.
Here is the link which describes doing so in a simple manner. Do give it a read. It may help you. Thanks
https://gun.io/blog/how-to-github-fork-branch-and-pull-request/

2016-12-03 08:20 UTC, Abhi2424shek commented
@Princu7 can you merge mine now!

2016-12-03 08:24 UTC, Princu7 commented
@Abhi2424shek Hehe. Don't worry. Your PR will be merged as soon as @daminisatya reviews and approves your changes. Cheers!!

2016-12-03 08:25 UTC, Abhi2424shek commented
@Princu7 i wait for then @daminisatya , k cheeres :) !!!

2016-12-03 08:51 UTC, Abhi2424shek commented
@hemantjadon can you now review

2016-12-03 09:34 UTC, Abhi2424shek commented
@jig08 can you help out @hemantjadon @Princu7

2016-12-03 09:40 UTC, Abhi2424shek commented
@jig08 let resolve the conflicts

2016-12-03 10:21 UTC, Abhi2424shek commented
@jig08 @Princu7 @mariobehling @hemantjadon @daminisatya Please squash and merge this PR before more problems arise :) , it's been a while and no responses :) 💯

2016-12-03 10:25 UTC, hemantjadon requested changes

2016-12-03 10:25 UTC, hemantjadon commented on index.html
> +<<<<<<< HEAD
Remove these Merge conflict tokens.

2016-12-03 10:58 UTC, Abhi2424shek commented
This is really complex now I will start a new PR

2016-12-03 10:58 UTC, closed without merging