Add Contributors Section
fossasia/gci16.fossasia.org pull request #15
Opened 2016-11-29 19:28 UTC by gaeun

I've added a "contributors section" to the GCI website showing the profile pictures, names, and number of commits of all the contributors to this repo.

2016-11-29 19:45 UTC, royalharsh commented
@gaeun Thanks for the pull request. Can you post the link to the website (via your github repo) for easier review?

2016-11-29 19:49 UTC, robbyoconnor requested changes
See comments.

2016-11-29 19:49 UTC, robbyoconnor commented on index.html
> +		        <aside id="sidebar">
Why is all of this trailing whitespace here?

2016-11-29 19:59 UTC, gaeun commented
@royalharsh https://github.com/gaeun/gci16.fossasia.org
@robbyoconnor Thanks, I didn't notice that. Just fixed it!

2016-11-29 20:00 UTC, royalharsh commented
Please squash your commits into one.

2016-11-29 20:52 UTC, royalharsh commented
This should help: [Squash your latest commits into one](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)

2016-11-29 20:58 UTC, gaeun commented
My git log doesn't show the last three commits I made, and only shows my first pull request. I'm not really sure why--is it because I edited the html file directly on Github?

2016-11-29 21:02 UTC, royalharsh commented
It might be possible because your local repo doesn't contain those changes you made directly on github. Try doing a `git pull` from your repo.

2016-11-30 02:13 UTC, daminisatya commented
@gaeun Great job, just try to resolve your conflicts. and it's good to go! :)

2016-11-30 02:40 UTC, robbyoconnor commented
Merge conflict resolution is a bit of a black art for newbies..

2016-11-30 03:43 UTC, gaeun commented
@royalharsh Ah finally fixed it :) I squashed all my commits.
@daminisatya I'll try and figure that out by tonight. Thanks!

2016-11-30 04:02 UTC, daminisatya commented
@gaeun Great job, Any doubt regarding resolving the conflict. You can contact any of the mentor.

2016-11-30 04:04 UTC, daminisatya commented
Please watch this[ video](https://www.youtube.com/watch?v=g8BRcB9NLp4) to clear the merge conflicts.

2016-11-30 13:49 UTC, gaeun commented
@daminisatya I think I've resolved all the conflicts. Thanks for the video link! That was helpful.

2016-11-30 13:51 UTC, daminisatya commented
Amazing, any final review from your side @robbyoconnor ?

2016-11-30 16:54 UTC, royalharsh commented
Great job and congrats on your first pull request! 😄

2016-11-30 16:55 UTC, merged