Added links to sections in the header.
fossasia/gci16.fossasia.org pull request #194
Opened 2016-12-04 18:22 UTC by Baidya99

It solves the issue https://github.com/fossasia/gci16.fossasia.org/issues/142

Even tough the links don't work on the live gh-pages of my fork (https://baidya99.github.io/gci16.fossasia.org/), I have tested it on the original and it works there.

2016-12-04 19:39 UTC, hemantjadon commented
Squash the commits please so that we can merge

2016-12-04 23:31 UTC, shubham-padia requested changes

2016-12-04 23:31 UTC, shubham-padia commented on index.html
> +        </div>
please remove the slashes preceding the `#` in the links, that is why the links are not working on your fork.

2016-12-05 05:06 UTC, Baidya99 commented on index.html
> +        </div>
how do we squash commits online

2016-12-05 05:09 UTC, Baidya99 commented
How to merge commits online.

2016-12-05 05:25 UTC, closed without merging