Added loklak tweets
fossasia/gci16.fossasia.org pull request #267
Opened 2016-12-07 13:33 UTC by Abhi2424shek

Added loklak tweets, work still in progress, the collabration is going on. Done my part, @PolBaldas it's your time to make the changes here's the url of the remote: `https://github.com/abhi2424shek/gci16.fossasia.org`

2016-12-07 15:15 UTC, PolBaladas commented
@Abhi2424shek gonna clone it now, do you know why id the Travis failing?

2016-12-07 15:19 UTC, Abhi2424shek commented
I will add a commit to fix it you work now, I will fix it after the whole work is over, so we can also fix together the future errors!

2016-12-07 15:22 UTC, PolBaladas commented
Okay!

2016-12-07 15:26 UTC, Abhi2424shek commented
Sure 😉

2016-12-07 15:48 UTC, PolBaladas commented
@Abhi2424shek Hi there, Are you reusing css classes from Last Issues section? Maybe you wanna rename them, change the class/css... If not the design will be dependant on the latest issues section.

2016-12-07 15:57 UTC, PolBaladas commented
@Abhi2424shek did you end up doing the API part?

2016-12-07 16:28 UTC, jigyasa-grover requested changes
* Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Refer the corresponding issue number in your commit message

2016-12-07 16:48 UTC, Abhi2424shek commented
@jig08 we r on collaboration, its being made I will inform you when it is done.

2016-12-08 14:09 UTC, Abhi2424shek commented
@gaeun welcome @PolBaladas mid incorporating her into as well @hemantjadon for this work you will accept us thrice right since she has also claimed the task and we don't want races.

2016-12-08 14:14 UTC, hemantjadon commented
@Abhi2424shek We want all of you to collaborate and make something awesome :) So no problems

2016-12-09 11:54 UTC, abishekvashok commented on javascripts/loklak-fetcher.js
> + ******************************************************************************/
See the header @PolBaladas

2016-12-09 12:25 UTC, Abhi2424shek commented
We'll come back soon,,, :)

2016-12-09 12:25 UTC, closed without merging