Added Student Projects Section (Issue #176)
fossasia/gci16.fossasia.org pull request #301
Opened 2016-12-08 17:31 UTC by hesapadim

https://github.com/fossasia/gci16.fossasia.org/issues/176

2016-12-08 17:33 UTC, m1guelpf commented
@hesapadim Please:
- Squash all your commits
- Add an usefull title to the commit

2016-12-08 17:46 UTC, hesapadim commented
@m1guelpf Fixed & added navbar but how can I update commits? I'm new to GitHub.

2016-12-08 18:17 UTC, oanarosca commented
Your new commit has been automatically added here. Please see why the travis build failed (maybe you used tabs instead of spaces, left some extra spaces or no line break at EOF), commit your changes and squash them into one commit. If you need help, check out contributors.md or join the slack channel. Good luck!

2016-12-09 18:34 UTC, niccokunzmann commented
@hesapadim Have a look into the contributing.md file. There is information about how to squast and force push. Also, you can have a look into the README.md file. There is written, where you can get even more supprt.

2016-12-09 20:36 UTC, m1guelpf requested changes
Please make the changes addressed

2016-12-09 20:36 UTC, m1guelpf commented on index.html
> +<<<<<<< HEAD
Remove the git tag

2016-12-09 20:36 UTC, m1guelpf commented on index.html
> +=======
Remove the git tag

2016-12-09 20:36 UTC, m1guelpf commented on index.html
> +>>>>>>> parent of 4d27f6b... test
Remove the git tag

2016-12-10 08:19 UTC, niccokunzmann commented
I am merging this, so we can have he projects section now and others can build on it, not later and maybe never because we force some rules. The merge lines are not visible on the website.

2016-12-10 08:20 UTC, merged

2016-12-10 08:21 UTC, niccokunzmann commented
@hesapadim Please address the changes. I create an issue.