Update blogs.yml
fossasia/gci16.fossasia.org pull request #329
Opened 2016-12-09 13:50 UTC by Kunal719

I want to upload my blog for GCI.

2016-12-09 13:56 UTC, m1guelpf commented on _data/blogs.yml
> +
Please remove trailing whitespace on line 54

2016-12-09 13:56 UTC, m1guelpf requested changes
Please make the changed addresed and provide your live gh-pages link.

2016-12-09 15:44 UTC, Kunal719 commented on _data/blogs.yml
> +
Someone else has taken that line. Now what to do??

2016-12-09 15:47 UTC, Kunal719 reviewed
Done

2016-12-09 15:48 UTC, Abhi2424shek commented on _data/blogs.yml
> +
Just remove that space.

2016-12-09 15:50 UTC, m1guelpf commented
@Kunal719 You have to fix the merge errors, check contribuiting.md for details.

2016-12-09 16:36 UTC, Kunal719 commented
Which Space? Can you please highight?

On 9 December 2016 at 21:20, Miguel Piedrafita <notifications@github.com>
wrote:

> @Kunal719 <https://github.com/Kunal719> You have to fix the merge errors,
> check contribuiting.md for details.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/329#issuecomment-266046570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXV9445AeG8Nnsxof32WFc8oT5QygSsoks5rGXipgaJpZM4LI9N5>
> .
>

2016-12-09 16:40 UTC, m1guelpf commented
@Kunal719 You have to fix the merge errors, you already fixed the space. Check contribuiting.md for help fixing merge

2016-12-09 16:44 UTC, Kunal719 commented
What is contributing.md ??

2016-12-09 16:45 UTC, oanarosca commented
[This](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) file.

2016-12-09 16:45 UTC, m1guelpf commented
@Kunal719 It is a file with help on contribuiting.
You can access it [here](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md)

2016-12-09 16:47 UTC, Kunal719 commented
So what to do with it? I have done the blog, made that "space" work corrected. Now What do you want?

2016-12-09 16:48 UTC, oanarosca commented
@Kunal719 please read that file to see how you must solve the merge conflicts. We cannot approve and merge your PR if there are merge conflicts.

2016-12-09 16:48 UTC, m1guelpf approved these changes

2016-12-09 16:51 UTC, Kunal719 commented
What are those merge conflicts?

2016-12-09 16:53 UTC, m1guelpf commented
@Kunal719 It means that your changes conflict with gh-pages changes, because we merged other PR's before yours and things changed.

2016-12-09 16:54 UTC, Kunal719 commented
Is my pull request approved?

2016-12-09 16:55 UTC, m1guelpf commented
@Kunal719 Not yet, you have to fix merge conflicts. I only approved my last review.

2016-12-09 16:57 UTC, Kunal719 commented
I am not getting how to merge these conflicts.

2016-12-09 18:30 UTC, rhemon commented
@Kunal719 have a look into the CONTRIBUTING.md file, it has links to good tutorials on merge conflicts.

2016-12-10 21:51 UTC, niccokunzmann commented
![capture](https://cloud.githubusercontent.com/assets/564768/21076420/082936ca-bf2b-11e6-80eb-ecbe3a0499db.PNG)
For me, there was a button. @Kunal719 Can you help me and others resolve their merge conflicts?

2016-12-10 21:51 UTC, merged