Added Student Image
fossasia/gci16.fossasia.org pull request #514
Opened 2016-12-13 15:12 UTC by dewanshrawat15

I've added my image in the students section.

2016-12-13 15:16 UTC, jigyasa-grover requested changes

2016-12-13 15:16 UTC, jig08 commented on CNAME
> +gci16.fossasia.org/
You arent supposed to change this file.

2016-12-13 15:16 UTC, jig08 commented on _data/students.yml
> +- # New members please add your credentials to the bottom of the file.
This change wasnt required too..

2016-12-13 15:16 UTC, jig08 commented on _data/students.yml
> +  github: dewanshrawat15
Improper indentation, refer previous entries.

2016-12-13 15:16 UTC, jig08 commented on index.html
> +<!-- I am cool-->
Why was this added ? 😅

2016-12-13 15:16 UTC, jig08 commented
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also Provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

2016-12-13 16:31 UTC, abishekvashok requested changes
Please fix as stated by @jig08 and remove the unwanted lines, bro we know you are cool so no need to imply it 👍 😂

2016-12-13 16:33 UTC, dewanshrawat15 commented
Sorry about that.😂 I'm currently working on that fix only...
What I'm unable to understand is how do I fix the image..?? This type of
HTML structure is a first for me and I'm unable to put my image up. Could
you possibly help me..??
On Dec 13, 2016 10:02 PM, "Abishek V Ashok" <notifications@github.com>
wrote:

> *@Abhi2424shek* requested changes on this pull request.
>
> Please fix as stated by @jig08 <https://github.com/jig08> and remove the
> unwanted lines, bro we know you are cool so no need to imply it 👍 😂
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/514#pullrequestreview-12719388>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQNyd9bH_E27NxMlPfIZcRnQgnLWIWIzks5rHsiAgaJpZM4LL14B>
> .
>

2016-12-13 19:19 UTC, ankitrgadiya commented
@dewanshrawat15 You don't have to touch index.html in order to put image. Go ahead and add your image name in students.yml as specified [here](https://github.com/fossasia/gci16.fossasia.org/#adding-yourselves-to-student-section).

2016-12-13 19:20 UTC, m1guelpf commented on index.html
> +<!-- I am cool-->
I think you should remove this :sweat_smile:

2016-12-14 01:23 UTC, dewanshrawat15 commented
****
***

2016-12-14 01:26 UTC, dewanshrawat15 commented
I have done the required changes.

2016-12-14 08:43 UTC, Abhi2424shek commented
Great work, now can you fix the merge conflicts by following the tutorials in the contributing.md file

2016-12-14 08:57 UTC, animeshsinghweb commented
@dewanshrawat15 Also there are some new conflicts problem in your `students.yml` file.
That's the reason it is suggest to isolate from the main branch (in this case it is **gh-pages** branch, make changes in your new branch, commit, recheck, squash, and then PR).
I'd even suggest you, from next time while requesting for Pull Request make a new branch using `git checkout -b yourNewBranchName` and then you can do your changes there, commit, squash and request for PR.

2016-12-14 16:42 UTC, dewanshrawat15 commented
Um, I guess I've done the required changes on my repository. What now..??
On Dec 14, 2016 2:27 PM, "Animesh Singh" <notifications@github.com> wrote:

> @dewanshrawat15 <https://github.com/dewanshrawat15> Also there are some
> new conflicts problem in your students.yml file.
> That's the reason it is suggest to isolate from the main branch (in this
> case it is *gh-pages* branch, make changes in your new branch, commit,
> recheck, squash, and then PR).
> I'd even suggest you, from next time while requesting for Pull Request
> make a new branch using git checkout -b yourNewBranchName and then you
> can do your changes there, commit, squash and request for PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/514#issuecomment-266978950>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQNydwomE75zNdKwmlSW91RfifRM9S1Rks5rH6-EgaJpZM4LL14B>
> .
>

2016-12-14 17:18 UTC, animeshsinghweb commented
@dewanshrawat15.
There is yet some conflict problem.
If you need Personal Assistant please DM me at Slack id animeshsinghweb

2016-12-14 17:36 UTC, m1guelpf commented
@dewanshrawat15 LGTM

2016-12-14 17:36 UTC, merged

2016-12-14 17:38 UTC, dewanshrawat15 commented
Good Evening
I just received a notification mail from github about the merge. Does that
mean my image will also appear on gci16.fossasia.org starting now..??

Regards
Dewansh
On Dec 14, 2016 11:06 PM, "Miguel Piedrafita" <notifications@github.com>
wrote:

> Merged #514 <https://github.com/fossasia/gci16.fossasia.org/pull/514>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/514#event-894004630>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQNyd6Q-x77DEV2FiX3UOIAWglpYHgjxks5rICk1gaJpZM4LL14B>
> .
>

2016-12-14 17:40 UTC, m1guelpf commented
@dewanshrawat15 Yep

2016-12-14 17:41 UTC, dewanshrawat15 commented
Don't know why I don't see it..😂
On Dec 14, 2016 11:10 PM, "Miguel Piedrafita" <notifications@github.com>
wrote:

> @dewanshrawat15 <https://github.com/dewanshrawat15> Yep
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/514#issuecomment-267101318>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQNyd0mES2Oo1YflhH0LW3s2DCt_I6mLks5rICoCgaJpZM4LL14B>
> .
>

2016-12-14 18:04 UTC, m1guelpf commented
@dewanshrawat15 Build is broken, fixed now