Removed hover, deleted grayscale. Added proper indent to the code and added <script>files to the <head> tag.
fossasia/gci16.fossasia.org pull request #57
Opened 2016-12-01 10:12 UTC by siddhant2001

The code is cleaner, there is no hover effect, page looks nice and simple.

2016-12-01 10:42 UTC, hemantjadon requested changes
Also Please provide the Task link and the link to your gh-pages of your fork.

2016-12-01 10:42 UTC, hemantjadon commented on index.html
> +  <script src="js/bootstrap.min.js"></script>
The first line in the head should be the `meta tags` not the `render-blocking` js and css loading

2016-12-01 10:42 UTC, hemantjadon commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
Add the proper EOL/EOF character `[CRLF]`. (Simply a new line at the end.

2016-12-01 10:42 UTC, hemantjadon commented on index.html
> +  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></scrip
Why double loading of `bootstrap.min.js` one at top in head and one here

2016-12-01 10:42 UTC, hemantjadon commented
Also please check for merge conflicts

2016-12-01 13:53 UTC, siddhant2001 commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
That is not my code.

2016-12-01 13:59 UTC, hemantjadon commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
The line was there before your commit.
And every line of code is ours not of any particular person.
If there is a bug and you can fixit you should.

2016-12-01 14:01 UTC, siddhant2001 commented on index.html
> +  <script src="js/bootstrap.min.js"></script>
The code doesn't work when I do that. Please let it be, the website works fine.

2016-12-01 14:01 UTC, siddhant2001 commented on index.html
> +  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></scrip
By mistake, removed it.

2016-12-01 14:02 UTC, siddhant2001 commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
I don't know what EOL/EOF character [CRLF] is.

2016-12-01 14:06 UTC, hemantjadon commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
Simply add a newline at the end of the file

2016-12-01 14:06 UTC, siddhant2001 commented on stylesheets/stylesheet.css
>  @media only screen and (max-width: 479px) { }
Ok

2016-12-02 08:36 UTC, hemantjadon requested changes

2016-12-02 08:36 UTC, hemantjadon commented on CNAME
> -gci16.fossasia.org
Why changing the removing the correct CNAME?

2016-12-02 08:38 UTC, hemantjadon commented
Please check the merge conflicts also

2016-12-03 09:26 UTC, jigyasa-grover reviewed
@siddhant2001 

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

2016-12-03 09:29 UTC, jig08 commented on CNAME
> -gci16.fossasia.org
I'd suggest you to read more about `CNAME`.
You arent supposed to change it :)

Links:
* https://help.github.com/articles/using-a-custom-domain-with-github-pages/
* https://en.wikipedia.org/wiki/CNAME_record

2016-12-03 09:31 UTC, hemantjadon approved these changes

2016-12-05 10:29 UTC, jig08 commented
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

2016-12-05 10:29 UTC, closed without merging