Added in Students section
fossasia/gci16.fossasia.org pull request #578
Opened 2016-12-16 15:11 UTC by gautamjajoo

I have added my details and uploaded my image on the website.

2016-12-16 15:24 UTC, abishekvashok requested changes

2016-12-16 15:24 UTC, Abhi2424shek commented on index.html
> ----
Don't remove these lines @gautamjajoo they are needed for jekyll, learn more about jekyll and gh-pages see here: https://help.github.com/categories/github-pages-basics/

2016-12-16 15:26 UTC, abishekvashok requested changes

2016-12-16 15:26 UTC, Abhi2424shek commented on index.html
> -                                        <i class="fa fa-code"></i>
You are adding the files to index.html, you should not do that, you only need to include your info to the students file and add your photo to the /images/students section, remember an image has to be 240x240 pixels [w x h]

2016-12-16 15:27 UTC, Abhi2424shek commented
@gautamjajoo ping me on slack if you want more help alwyas there to help you out :)

2016-12-17 03:18 UTC, Princu7 commented
@gautamjajoo Please resolve the merge conflicts. You can learn more about them in the contribution guide of this project. If you need more assistance, you can also ask us here on ping us on the slack or the gitter channel.
Cheers!

2016-12-17 06:18 UTC, Abhi2424shek commented
You again got it wrong, there is no need to touch the index.html file bro just add your data to the _data/students.yml page and add your image that's. :) Try again... , Happy coding :)

2016-12-17 06:31 UTC, abishekvashok approved these changes

2016-12-17 06:31 UTC, Abhi2424shek commented
@gautamjajoo nice work now :)

2016-12-17 06:33 UTC, merged