Improve contribution section
fossasia/gci16.fossasia.org pull request #592
Opened 2016-12-17 21:12 UTC by AKostiv8

2016-12-17 21:20 UTC, AKostiv8 commented
https://akostiv8.github.io/gci16.fossasia.org/

2016-12-17 21:21 UTC, AKostiv8 commented
https://codein.withgoogle.com/dashboard/task-instances/5974474228760576/

2016-12-17 21:53 UTC, gaeun commented
Can you use the Github API, and not a static array of the contributors?

2016-12-18 06:13 UTC, abishekvashok requested changes
Please use github api, we already have a contributors section please try to enhance it and make use of github api.

2016-12-18 06:13 UTC, Abhi2424shek commented on javascripts/contributors.js
> +      "BohJieQi",
Dont use static array use the github api because in it contributors are added automatically...

2016-12-18 09:04 UTC, AKostiv8 commented
I don't know how to use Github API

2016-12-18 20:29 UTC, AKostiv8 commented
@niccokunzmann

2016-12-18 21:22 UTC, niccokunzmann commented
@AKostiv8 How would you like to go on? Do you have plans? Would you like suggestions?

2016-12-19 21:49 UTC, AKostiv8 commented
hurry up!!! I have done it))))))

2016-12-19 21:55 UTC, gaeun commented
@AKostiv8 I visited your live link, and it seems like the contributors aren't showing up... But I think a bit of debugging would make it work! Great job!

2016-12-19 22:08 UTC, robbyoconnor requested changes
If we include vendor prefixes in our CSS, we should include them for other browsers as well..

2016-12-19 22:08 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -webkit-animation-iteration-count: infinite;
Same here

2016-12-19 22:08 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -webkit-animation-iteration-count: infinite;
Same here.

2016-12-19 22:08 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -webkit-transform: translate(-50%, -50%);
We need to support other browsers too...not just webkit browsers...if you're gonna use vendor-prefixes handle them all.

2016-12-20 03:24 UTC, robbyoconnor commented
@AKostiv8, are you going to fix this?

2016-12-20 08:25 UTC, Abhi2424shek commented
@AKostiv8 nice job, keep up the good work :)

2016-12-20 13:58 UTC, AKostiv8 commented
@Abhi2424shek @robbyoconnor  I have fixed your requested

2016-12-20 15:51 UTC, abishekvashok approved these changes

2016-12-20 15:52 UTC, Abhi2424shek commented
@AKostiv8 nice work, bro can you squash your commits see the contributing.md file for info and tutorials on squashing if they don't help ping me on slack I would help you out for sure so happy coding :)

2016-12-20 16:40 UTC, AKostiv8 commented
@Abhi2424shek  thanks for supporting

2016-12-20 18:06 UTC, AKostiv8 commented
@Abhi2424shek  I have squashed it

2016-12-20 21:02 UTC, robbyoconnor requested changes
The mozilla vendor prefix is incorrect.

2016-12-20 21:02 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -mos-transform: translate(-50%, -50%);
Don't you `moz-transform`

2016-12-20 21:02 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -mos-animation-iteration-count: infinite;
The prefix for mozilla is `moz`

2016-12-20 21:02 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  -mos-animation-iteration-count: infinite;
`moz`

2016-12-20 21:05 UTC, robbyoconnor commented
Here is a [guide on vendor prefixes](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix).

2016-12-20 21:07 UTC, robbyoconnor commented
@Abhi2424shek DO NOT MERGE! The vendor prefixes for firefox are incorrect.

2016-12-20 21:14 UTC, robbyoconnor commented
Also there's a quirk with the thing thanking contributors: 
![image](https://cloud.githubusercontent.com/assets/23088/21368179/67a8db22-c6cf-11e6-8a49-efb1b9d0b536.png)

2016-12-20 22:46 UTC, robbyoconnor commented
@AKostiv8 you still have problems you have to fix. Learn about the vendor prefixes please :wink:

2016-12-21 09:44 UTC, Abhi2424shek commented
@AKostiv8 status

2016-12-21 09:45 UTC, Abhi2424shek commented
> @Abhi2424shek DO NOT MERGE! The vendor prefixes for firefox are incorrect.
@robbyoconnor I would only merge after proper testing

2016-12-21 09:56 UTC, robbyoconnor commented
Everything is perfect but the spacing on the ticker thingy is awkward

![image](https://cloud.githubusercontent.com/assets/23088/21384723/b511c300-c739-11e6-97d1-4770ad1175c3.png)

Either center it in that whitespace or clean it up. As it stands, it's not good.

2016-12-21 09:56 UTC, robbyoconnor requested changes

2016-12-21 09:56 UTC, robbyoconnor commented on stylesheets/contributors.css
> +  height: 50px;
Needs to be reduced. Play around with it a bit...

2016-12-21 09:58 UTC, abishekvashok requested changes
Please fix as suggested

2016-12-21 10:02 UTC, AKostiv8 commented
@robbyoconnor  I have fixed requested

2016-12-21 10:04 UTC, AKostiv8 commented
@robbyoconnor  @Abhi2424shek  can you approved

2016-12-21 10:04 UTC, AKostiv8 commented
?

2016-12-21 10:05 UTC, Abhi2424shek commented
@AKostiv8 @robbyoconnor looks good for me:
![image](https://cloud.githubusercontent.com/assets/8947010/21385050/044c720e-c793-11e6-9fd9-0c554bae6a93.png)

@robbyoconnor waiting for you sir

2016-12-21 10:05 UTC, abishekvashok approved these changes

2016-12-21 10:05 UTC, Abhi2424shek commented
@AKostiv8 can you squash the commits.

2016-12-21 18:53 UTC, robbyoconnor approved these changes

2016-12-21 18:54 UTC, robbyoconnor commented
Merging.

2016-12-21 18:54 UTC, merged

2016-12-21 19:12 UTC, nolik2000 commented
thanks

2016-12-21 19:14 UTC, nolik2000 commented
@robbyoconnor  can you approve?
https://codein.withgoogle.com/dashboard/task-instances/5974474228760576/