Gh pages
fossasia/gci16.fossasia.org pull request #640
Opened 2016-12-21 19:30 UTC by zahariasp

New buttons created

2016-12-21 19:39 UTC, gaeun commented
Can you resolve the merge conflicts?

2016-12-21 22:02 UTC, robbyoconnor commented
You have conflicts. 

Also, you need to make your photo `240x240`.

2016-12-21 22:07 UTC, robbyoconnor commented
Also your PR title needs to be more descriptive @zahariasp.

2016-12-22 22:44 UTC, robbyoconnor commented
@zahariasp you need to resolve these merge conflicts.

2016-12-23 06:59 UTC, abishekvashok requested changes

2016-12-23 06:59 UTC, Abhi2424shek commented on index.html
>                          </div>
Dont name IDs after your names

2016-12-23 06:59 UTC, Abhi2424shek commented on javascripts/main.js
> +  btn.style.opacity = 0.6;
Use css for opacities see the pseudo selectors

2016-12-23 07:00 UTC, Abhi2424shek commented
You can check the merge conflicts resolving tutorials in the contributing.md file or you could ping me on slack @zahariasp

2016-12-23 07:22 UTC, robbyoconnor commented
@Abhi2424shek -- he's gonna have to resolve conflicts -- his code could change significiantly...so the review was premature.

2016-12-25 07:11 UTC, robbyoconnor requested changes
Fix merge conflicts, resize your photo

2016-12-26 11:19 UTC, robbyoconnor commented
@zahariasp I am closing this PR due to lack of activity.

2016-12-26 11:19 UTC, closed without merging

2016-12-26 11:19 UTC, robbyoconnor commented
Please open a new one when you are ready.