Fix linter issues
fossasia/gci16.fossasia.org pull request #656
Opened 2016-12-24 13:00 UTC by yukiisbored

This are fixes for issues reported by coala

I hope you have a very awesome holiday!

Cheers

2016-12-24 13:08 UTC, ankitrgadiya commented on index.html
> +            <section id="contributors-thanks" href="#contributors">
Why you removed "Thanks contributors section"?

2016-12-24 13:08 UTC, ankitrgadiya commented on .travis.yml
> -  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/coala_patch.sh; fi'
Why are you removing this??

2016-12-24 13:13 UTC, yukiisbored commented on .travis.yml
> -  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/coala_patch.sh; fi'
Read the commit message
https://github.com/fossasia/gci16.fossasia.org/pull/656/commits/a9a518148de424626d5b96c4c03b5fe4e37668c3

2016-12-24 13:13 UTC, yukiisbored commented on index.html
> +            <section id="contributors-thanks" href="#contributors">
I didn't, Read the diffs below

2016-12-24 13:19 UTC, ankitrgadiya approved these changes

2016-12-24 13:19 UTC, ankitrgadiya commented on index.html
> +            <section id="contributors-thanks" href="#contributors">
Okay Sorry my bad @yukiisbored

2016-12-24 13:19 UTC, yukiisbored commented
@robbyoconnor Sorry to annoy you, but Can you fix @checkbot ?

2016-12-24 13:22 UTC, ankitrgadiya commented
@yukiisbored Check this as you are changing the index.html file intentionally.

2016-12-24 13:22 UTC, yukiisbored commented
@ankitrgadiya What do you mean by "this" ?

2016-12-24 13:23 UTC, ankitrgadiya commented
@yukiisbored Oops! forgot to add link. [Here](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/maintainers.md#notes-for-mantainers)

2016-12-24 13:24 UTC, yukiisbored commented
@ankitrgadiya "PR Body" as in the PR message, right?

2016-12-24 13:27 UTC, ankitrgadiya commented
Yeah

2016-12-24 14:29 UTC, yukiisbored commented
Can I please see the details for `percy`?

2016-12-24 15:00 UTC, yukiisbored commented
I don't see any differences with both live and my branch. Can I please see the details for percy?

2016-12-24 15:11 UTC, Abhi2424shek commented
Wow, not even the maintainers have access!

2016-12-24 19:22 UTC, robbyoconnor requested changes

2016-12-24 19:22 UTC, robbyoconnor commented on .travis.yml
> +    coala --ci"
No need for this. `--ci is already passed on Line 15

2016-12-24 19:23 UTC, robbyoconnor commented
percy is gonna see a difference...we're changing things...just ignore percy failing...

2016-12-24 19:49 UTC, jayvdb commented on .travis.yml
> +    coala --ci"
Wow; it was running twice. Ouch.
So this PR should help solve https://github.com/fossasia/gci16.fossasia.org/issues/226 .

2016-12-24 20:01 UTC, robbyoconnor commented on .travis.yml
> +    coala --ci"
@jayvdb it's being run twice still unless line 16 is removed...I added `--ci` I will make this chnage -- back this change out @yukiisbored

2016-12-24 20:07 UTC, robbyoconnor commented on .travis.yml
> +    coala --ci"
I merged #665 - which made this change -- @yukiisbored -- to resolve this -- just back this change out..when you'll get a conflict -- just take what's currently in `gh-pages` branch in this repo.

2016-12-24 20:10 UTC, robbyoconnor approved these changes

2016-12-24 20:11 UTC, robbyoconnor commented
@yukiisbored -- I resolved the merge conflict for you -- no work needs to be done on your part! 

Are we good to merge this everybody?

Also Happy Holidays!

2016-12-24 20:29 UTC, robbyoconnor commented
Merging this -- as now Travis fails if we don't have good code and you fixed issues that are failing.

2016-12-24 20:29 UTC, merged

2016-12-24 23:20 UTC, robbyoconnor commented
You broke things...I should have checked closer...

2016-12-25 01:20 UTC, yukiisbored commented
@robbyoconnor The one that says `[ Thanks to contributors <name> ]` That's already broken to begin with.

2016-12-25 01:21 UTC, yukiisbored commented
Because it uses `list` instead of `span`

2016-12-25 01:22 UTC, robbyoconnor commented
I'm in favor of nuking it.

On Dec 24, 2016 20:20, "Kaisar Arkhan (Yuki)" <notifications@github.com>
wrote:

@robbyoconnor <https://github.com/robbyoconnor> The one that says [ Thanks
to contributors <name> ] That's already broken to begin with.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/gci16.fossasia.org/pull/656#issuecomment-269106464>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AABaMOogIGB8l6Ttkca8P4SGozTgKh0xks5rLcTbgaJpZM4LVONh>
.

2016-12-25 01:34 UTC, yukiisbored commented
@robbyoconnor Are you serious? Do you really want to remove that section?

2016-12-25 01:38 UTC, robbyoconnor commented
I mean either that or fix it...brownie points for fixing it :D

On Dec 24, 2016 20:34, "Kaisar Arkhan (Yuki)" <notifications@github.com>
wrote:

> @robbyoconnor <https://github.com/robbyoconnor> Are you serious? Do you
> really want to remove that section?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/656#issuecomment-269106726>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABaMFnk4y0_sbeMP_unVBpNFylCUwwBks5rLcgWgaJpZM4LVONh>
> .
>