Adding my photo and credential to the website
fossasia/gci16.fossasia.org pull request #67
Opened 2016-12-01 15:39 UTC by Heredroky

2016-12-01 15:41 UTC, Heredroky commented
Preview: https://heredroky.github.io/gci16.fossasia.org/index.html

2016-12-01 16:58 UTC, hemantjadon commented
Just resolve the conflicts and you are good to go.

2016-12-01 17:02 UTC, Heredroky commented
Which are the conflicts?

2016-12-01 17:09 UTC, hemantjadon commented
Merge conflicts

2016-12-01 17:14 UTC, Heredroky commented
Ok, but please wait a minute

2016-12-01 17:50 UTC, Heredroky commented
I think it is ready

2016-12-01 17:56 UTC, hemantjadon commented
Okay this seems pretty good to me.

But the blog section made by @rhemon seems not to be working. Please check. Then you are good to go.

2016-12-01 18:05 UTC, Heredroky commented
I've checked many times what's happening with that, but I don't what's causing that problem :(

2016-12-01 18:13 UTC, hemantjadon commented on index.html
> ----
You have removed these dashes which are important for jekyll add them and things will work out

2016-12-01 18:22 UTC, Heredroky commented on index.html
> ----
ok, I will correct it, thank you :)

2016-12-01 18:35 UTC, Heredroky commented on index.html
> ----
No, it isn't working yet :/
https://heredroky.github.io/gci16.fossasia.org/index.html

2016-12-01 18:46 UTC, Heredroky commented on index.html
> ----
But I will try to fix that

2016-12-01 23:10 UTC, rhemon commented
@heredroky at the top of the html to work jekyll you need to have 
---
---
note: they must be on two separate lines, you have only added once. 
hope it helps :)

2016-12-01 23:12 UTC, rhemon commented
sorry it should be this
"---"

"---"
in previous comment it seems it changed without comment (dont add the double quote)

2016-12-01 23:14 UTC, Heredroky commented
Do you mean something like this?

---
---

2016-12-01 23:15 UTC, Heredroky commented
"---"
"---"

2016-12-01 23:17 UTC, rhemon commented
yes

2016-12-01 23:29 UTC, Heredroky commented
Thank you Thank you Thank you Thank you Thank you Thank you Thank you :D It worked!!!
Now I need that someone merges that

2016-12-01 23:30 UTC, rhemon commented
haha. no problems. congrats :)

2016-12-02 00:07 UTC, tradzik requested changes
Commits should be [squashed](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before we can merge it. Adding 11 commits with the same purpose causes mess.

2016-12-02 01:42 UTC, closed without merging