Fix the Thanks section's displaying issues
fossasia/gci16.fossasia.org pull request #739
Opened 2016-12-29 10:02 UTC by hoangvanthien

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request (replace the text as instructed)

- Fix #647 
- Besides, there WAS another problem not mentioned: contributors section didn't display all people. It somehow stopped fetching.
![screen shot 2016-12-29 at 16 48 04](https://cloud.githubusercontent.com/assets/11438948/21541237/52b5b3f6-cde7-11e6-965a-5b8bccdbe327.png)
- I remove `contributors.js` because it is more convenient to fetch contributors list ONCE in `main.js`.

Comments: The simple solution for the #647 is adjusting `margin-top`. However, I found a really serious bug in `contributors.js` that variable `j` is not handled when it reaches the ending iterator of the array --> runtime error. Moreover, the JS code changing html content of `#name` **must not** be run in recursive function (i.e. while fetching the list). They are all fixed.

Live link: https://hoangvanthien.github.io

2016-12-29 10:51 UTC, gaeun commented
LGTM, thanks!

2016-12-29 11:06 UTC, robbyoconnor commented
@hoangvanthien there's a quirk you need to fix: 
![image](https://cloud.githubusercontent.com/assets/23088/21542606/f4881076-cd8c-11e6-80b0-32b1e76cbacd.png)
It looks bad...

2016-12-29 11:08 UTC, robbyoconnor requested changes
Aside from that one quirk I mentioned, this is good...fix that and it's good to merge!

2016-12-29 11:09 UTC, hoangvanthien commented
Erm... @robbyoconnor 
What browser and screen resolution are you using?
![screen shot 2016-12-29 at 18 07 50](https://cloud.githubusercontent.com/assets/11438948/21542651/dbb95982-cdf1-11e6-915b-9368aab100d1.png)

2016-12-29 11:24 UTC, codein-dwij commented
http://prntscr.com/dp96jd 
Seems Fine for me :)

2016-12-29 12:10 UTC, robbyoconnor commented
Google Chrome 56.0.2924.28

2016-12-29 12:11 UTC, robbyoconnor commented
@codein-dwij -- it looks fine when the names come in...it's BEFORE the names are loaded that the issue arises. Look at my screenshot closely.

2016-12-29 12:12 UTC, robbyoconnor commented
Oh Resolution is 1366x768

2016-12-29 12:40 UTC, robbyoconnor commented
Still showing a problem: 

![image](https://cloud.githubusercontent.com/assets/23088/21544062/02afe40a-cd9a-11e6-9a56-b6f44d4c1fd7.png)

2016-12-29 12:41 UTC, robbyoconnor commented
You have to account for the loading of the contributers to be delayed, so `everyone`(the filler text) shows.

2016-12-30 00:15 UTC, robbyoconnor commented
Just double checking things -- sorry for noise.

2016-12-30 05:49 UTC, robbyoconnor commented
bump!

2016-12-30 11:55 UTC, ankitrgadiya commented
@hoangvanthien Please fix this. It's not looking good on small window.
![screenshot from 2016-12-30 17-24-29](https://cloud.githubusercontent.com/assets/18071765/21564550/e1da5be0-ceb4-11e6-8ef1-f5d942d8cbcd.png)

2016-12-30 20:39 UTC, robbyoconnor commented
@ankitrgadiya and if the contributors list isn't loaded -- everyone clobbers the `Thank you you for your contribution,` -- This whole feature is nice and all but it never really worked out all that well.

2016-12-31 05:31 UTC, robbyoconnor commented
@hoangvanthien you working on this?

2016-12-31 05:52 UTC, hoangvanthien commented
@robbyoconnor I am. Sorry for being quiet quite long. I had some other businesses that are done now.

2016-12-31 06:56 UTC, robbyoconnor commented
@hoangvanthien CI failing is your fault: 
Here's what Coala said: 
```
|    | [MAJOR] BootLintBear:
|    | Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-xs-12 col-sm-12 col-md-12 col-lg-12"` is redundant and can be simplified to `class="col-xs-12"`
```

2016-12-31 06:57 UTC, robbyoconnor requested changes

2016-12-31 06:57 UTC, robbyoconnor commented on index.html
> +                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
change to `col-xs-12` please.

2016-12-31 06:58 UTC, robbyoconnor approved these changes

2016-12-31 07:00 UTC, robbyoconnor requested changes
Accidentally approved -- make the changes I mentioned and push it

2016-12-31 07:23 UTC, hoangvanthien commented
I'm going to close this for experimenting. I will reopen it later.

2016-12-31 07:24 UTC, closed without merging

2016-12-31 08:48 UTC, hoangvanthien commented on index.html
> +                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
It is not simple as that, I tried. Anyway I fixed it here #759.