adding photo to html
fossasia/gci16.fossasia.org pull request #75
Opened 2016-12-01 19:44 UTC by AlexTurning

2016-12-01 23:58 UTC, tradzik requested changes
Please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits into one and rebase to make this PR easily mergable. Thanks.

2016-12-01 23:58 UTC, tradzik commented on index.html
> +					  <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
Please improve tabulation in this line.

2016-12-01 23:58 UTC, tradzik commented on _data/students.yml
> +
Please remove empty line at the end of the file.

2016-12-02 05:10 UTC, hemantjadon commented
@AlexTurning please also resolve the merge conflicts

2016-12-02 10:28 UTC, jig08 commented
@AlexTurning As @tradzik & @hemantjadon pointed, pls do the following:

* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students/mentors section"
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful. 

Cheers !

2016-12-05 10:30 UTC, jig08 commented
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

2016-12-05 10:31 UTC, closed without merging