Adding myself as a student and added a project
fossasia/gci16.fossasia.org pull request #768
Opened 2016-12-31 20:38 UTC by muhammednagy

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- i added myself as a student and added my blog

2016-12-31 20:52 UTC, Elgayar commented
@muhammednagy Hey, please add a live link or a screenshot and write a description for your pull request!

2017-01-01 00:09 UTC, robbyoconnor requested changes
please resize your image to 240x240

2017-01-01 07:09 UTC, abishekvashok requested changes
**To resolve merge conflicts follow the tutorial here:  https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/**

And remember github provides you to host your repository on it, so if you are on the gh-pages or master branch you can deploy your site online with github, since you are on the gh-pages you are ready to go.
**So to see your repository online you have to go to [live link]:** `https://username.github.io/repository_name/`
**In your case it for this repository (meaning your fork) it should be [live link]:** https://muhammednagy.github.io/gci16.fossasia.org/

Then generate the screenshot, on Linux and Windows this is achieved by pressing `Ctrl + PrtScn`

**You should add the description where the PR body states it to specify and not to the top please do follow our coding practices for good results**.

_Note: You can change the SSL on and off for it. Just go to settings to do so!_

happy coding :)

2017-01-01 07:09 UTC, Abhi2424shek commented on _data/blogs.yml
> +
Yikes there is a trailing white space please remove it

2017-01-01 10:29 UTC, robbyoconnor commented on _data/blogs.yml
> +
coala will take care if it

2017-01-01 10:30 UTC, robbyoconnor requested changes

2017-01-01 10:30 UTC, robbyoconnor commented on _data/blogs.yml
> +  artivle_link: https://blog.muhnagy.com
Typo here.

2017-01-01 13:42 UTC, robbyoconnor commented
@muhammednagy, we fixed a lot of the issues. You did not actually read those checkboxes. it said 240x240. I unchecked it. Please check it when you actually completed the steps.

2017-01-01 13:54 UTC, Abhi2424shek commented on _data/blogs.yml
> +
I take it back sorry.

2017-01-01 14:07 UTC, closed without merging

2017-01-01 14:23 UTC, robbyoconnor commented
@muhammednagy I got charitable and fixed all issues. Next time, be sure you read things **_closely_**. That said, please submit your task so I can approve it.

2017-01-01 14:27 UTC, robbyoconnor commented
I fixed it.
On 01/01/2017 08:54 AM, Abishek V Ashok wrote:
> *@Abhi2424shek* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In _data/blogs.yml
> <https://github.com/fossasia/gci16.fossasia.org/pull/768>:
>
> > @@ -183,7 +183,7 @@
>    blog_img: adarsh-blog3.png
>    article: My experience with Fossasia
>    article_link: https://idealadarsh.wordpress.com/2016/12/12/my-experience-with-fossasia/
> -
> +  
>
> I take it back sorry.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/768>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AABaMI26c8YSvnjoRdWjPzz-4v0--iOSks5rN7AngaJpZM4LYnda>.
>

2017-01-27 19:13 UTC, muhammednagy commented
Thanks 
i had exams and i was busy. i was unable to fix my commit or see this comments 
i won't do it again 
thanks again @robbyoconnor

2017-01-28 06:14 UTC, Abhi2424shek commented
No probs we would be more happy to see some of your PRs merged @muhammednagy