Google code in
fossasia/gci16.fossasia.org pull request #778
Opened 2017-01-01 14:42 UTC by abdulsamad234

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- I added michael christen to the mentors section. The live view is abdulsamad234.github.io/gci16.fossasia.org and my task link is: https://codein.withgoogle.com/dashboard/task-instances/4796878325547008/

2017-01-01 14:45 UTC, Elgayar commented
Can you please provide a live link? or a screenshot.

2017-01-01 14:46 UTC, Abhi2424shek commented
It's there @Elgayar

2017-01-01 14:47 UTC, abishekvashok requested changes
Can you add some other details as well search his github, website or other things such as gutter for info or ping him itself

2017-01-01 14:49 UTC, robbyoconnor requested changes

2017-01-01 14:49 UTC, robbyoconnor commented on _data/mentors.yml
> +  image: michael.png
add more details...github, bio,etc.

2017-01-01 14:49 UTC, Elgayar commented
One more thing, next time, choose a more relevant pull request title..

2017-01-01 17:02 UTC, abishekvashok approved these changes

2017-01-01 17:03 UTC, Abhi2424shek commented
Nice work do you know to squash if you want to learn checkout the tutorials in the contributing.md file pls if not I will merge now itself just tell your opinion

2017-01-01 17:05 UTC, Abhi2424shek commented
@abdulsamad234 pls reply if you could or not mergin for you... Nice work

2017-01-01 17:07 UTC, merged

2017-01-01 18:06 UTC, abdulsamad234 commented
i don't know how to merge

2017-01-01 18:06 UTC, abdulsamad234 commented
please help am new to this whole thing @Abhi2424shek

2017-01-01 22:05 UTC, robbyoconnor commented on _data/mentors.yml
> +  github: abdulsamad234
Are you kidding me? HIS GITHUB, NOT YOURS!

2017-01-01 22:09 UTC, robbyoconnor commented on _data/mentors.yml
> +  twitter: nitrocoder2
His twitter NOT YOURS! How is this not clear?

2017-01-01 22:12 UTC, robbyoconnor commented
@abdulsamad234 Can you please explain to me why you added **_YOUR_** Twitter and **_YOUR_** github here? Not only that -- find their actual name, their actual twitter...I've reverted this -- trash your fork and start over.

2017-01-02 00:56 UTC, robbyoconnor commented
@abdulsamad234 -- softened up the tone a bit: also you might want to read the [contributing guidelines](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) -- which you checked that you read....I get this feeling you just checked them mindlessly -- do not do this! Please put forth some effort, i know you can do it.

2017-01-02 13:16 UTC, abdulsamad234 commented on _data/mentors.yml
> +  github: abdulsamad234
am sorry about that, i could not find his github

2017-01-02 13:16 UTC, abdulsamad234 commented on _data/mentors.yml
> +  twitter: nitrocoder2
also couldn't

2017-01-02 13:17 UTC, abdulsamad234 commented
Okay okay, i was just frustrated, i will start all over

2017-01-02 23:18 UTC, robbyoconnor commented
@abdulsamad234 -- You were frustrated so you added your github to a mentor's profile? How does that even make sense? 

Yes, you will start over...because I completely reverted it...Literally if you search -- you'll find their github, twitter, blog, etc. I told you how to do it already.

2017-01-02 23:20 UTC, robbyoconnor commented on _data/mentors.yml
> +  github: abdulsamad234
If you can't find it -- don't add ANY -- NEVER add your own. EVER!

2017-01-02 23:21 UTC, robbyoconnor commented on _data/mentors.yml
> +  github: abdulsamad234
He has github obviously -- he's a mentor.