Update students.yml
fossasia/gci16.fossasia.org pull request #826
Opened 2017-01-04 19:37 UTC by ariqzuhdi

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# *Do not* delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-01-04 19:56 UTC, robbyoconnor requested changes

2017-01-04 19:56 UTC, robbyoconnor commented on _data/students.yml
> +  image: ariqzuhdi.jpg
Where is this image @ariqzuhdi ?

2017-01-04 20:02 UTC, ariqzuhdi commented
In the images/students sir.

2017-01-04 20:07 UTC, robbyoconnor commented
Is it? I don't see it in the PR.

2017-01-04 20:08 UTC, robbyoconnor commented
Look at the included files.

2017-01-04 20:44 UTC, robbyoconnor commented
Please update this pull request with all the information. You never uploaded the file.

2017-01-04 21:53 UTC, robbyoconnor commented
@ariqzuhdi -- Also you didn't even bother to read the pull request template. Go read that.

2017-01-05 02:03 UTC, abishekvashok requested changes
Please and your image in 240x240 pixels and read the PR body (template) pls

2017-01-05 02:08 UTC, robbyoconnor commented
@Abhi2424shek what image?

2017-01-05 05:43 UTC, ariqzuhdi commented
Sorry i was sleepy, i. Fix it as soon as possible

On Jan 5, 2017 9:08 AM, "robbyoconnor" <notifications@github.com> wrote:

@Abhi2424shek <https://github.com/Abhi2424shek> what image?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/gci16.fossasia.org/pull/826#issuecomment-270545006>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ATTblNso9tA_tW3DhBLHalOMJpOnfFnNks5rPFCMgaJpZM4La_IE>
.

2017-01-05 06:27 UTC, robbyoconnor commented
No problem -- you need sleep -- you're young!

2017-01-05 07:40 UTC, ariqzuhdi commented
Umm, i have added it sir.

On Jan 5, 2017 1:27 PM, "robbyoconnor" <notifications@github.com> wrote:

> No problem -- you need sleep -- you're young!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/826#issuecomment-270573564>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATTblD72Czcf91KRHnfuzVGTloJeFPXRks5rPI1WgaJpZM4La_IE>
> .
>

2017-01-05 08:29 UTC, robbyoconnor commented
@ariqzuhdi No you did not. Add it to the `patch-1` branch.

2017-01-05 08:42 UTC, ariqzuhdi commented
Ahh sorry, wrong branch >.<

On Jan 5, 2017 3:30 PM, "robbyoconnor" <notifications@github.com> wrote:

> @ariqzuhdi <https://github.com/ariqzuhdi> No you did not. Add it to the
> patch-1 branch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/826#issuecomment-270589782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATTblG3EfjHozTRb_IdUQmmZ3mcSpe0Pks5rPKoGgaJpZM4La_IE>
> .
>

2017-01-05 09:05 UTC, robbyoconnor commented
Build failure isn't your fault.

2017-01-05 09:19 UTC, merged