add aditya mukti as participance
fossasia/gci16.fossasia.org pull request #852
Opened 2017-01-07 13:54 UTC by skywrapper

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-01-07 14:35 UTC, Elgayar commented
Please resolve the conflicts, check the boxes and write a description so that we can merge!

2017-01-07 15:35 UTC, abishekvashok requested changes
@skywrapper nice to see you here.

Please resize your image (i meant your and not the blog one) to exactly 240x240 pixels yours is 241x238 pixels, pls rectify it and update the PR body after reading it thoroughly, besides that there was a conflict which however we are resolving for now but next time I want to see you resolving conflicts cause we want you to learn ;)

Happy coding, please fix the image so that we could merge.

2017-01-07 15:36 UTC, Abhi2424shek commented
And if possible squash your commits

2017-01-07 21:17 UTC, robbyoconnor requested changes
Resize images.

2017-01-07 21:17 UTC, robbyoconnor commented
@skywrapper please read the text in the text that was there when you opened it.

2017-01-07 21:18 UTC, robbyoconnor commented
@skywrapper also your blog screenshot looks rather distorted..

2017-01-08 09:32 UTC, robbyoconnor requested changes
- Add image
- Image name cannot contain spaces
- FB usernames also may not contain spaces.

2017-01-08 09:32 UTC, robbyoconnor commented on _data/students.yml
> +  image: aditya mukti.png
Image name cannot have spaces.

2017-01-08 09:32 UTC, robbyoconnor commented on _data/students.yml
> +  facebook: Muhammad Aditya Mukti Nugroho
FB username cannot have spaces.

2017-01-08 09:33 UTC, robbyoconnor commented
Also resolve merge conflicts.

2017-01-09 06:36 UTC, robbyoconnor commented
@skywrapper you around?

2017-01-09 06:52 UTC, skywrapper reviewed
i  change the mistake with space between my facebook name, i re upload my photo with thr right size. and change the my sutudent photo name whitput space.

2017-01-09 07:12 UTC, robbyoconnor commented
@skywrapper 

- [Resolve the conflict](https://github.com/fossasia/gci16.fossasia.org/pull/852/conflicts)
- Your blog screenshot is skewed -- fix that.

2017-01-09 07:15 UTC, robbyoconnor requested changes
Facebook username is non-existent.

2017-01-09 07:15 UTC, robbyoconnor commented on _data/students.yml
> +  facebook: MuhammadAdityaMuktiNugroho
There is no profile.

2017-01-09 14:43 UTC, skywrapper reviewed
i change my fb profile

2017-01-09 15:00 UTC, skywrapper reviewed
i change my photo blog

2017-01-09 15:33 UTC, Abhi2424shek commented
Can you update the pr body

2017-01-10 11:16 UTC, Abhi2424shek commented
@skywrapper please update the PR body!

2017-01-10 19:46 UTC, robbyoconnor commented
@skywrapper please delete your fork and re-add yourself. I am going to close this pull request since it's now a disaster zone.

2017-01-10 19:46 UTC, closed without merging

2017-01-10 19:46 UTC, robbyoconnor commented
@skywrapper when you readd yourself -- read the first line of the file and add yourself to a random location.

2017-01-11 01:45 UTC, skywrapper commented
sorry for the mistake, i am trying to squash the commit and push them. i
read the guide in someone blog, but i dont know it will push all the
commits.
but i will re join this task with other account in gci because i already
abandon the task in gci
thanks for the guide

2017-01-11 3:46 GMT+08:00 robbyoconnor <notifications@github.com>:

> @skywrapper <https://github.com/skywrapper> when you readd yourself --
> read the first line of the file and add yourself to a random location.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci16.fossasia.org/pull/852#issuecomment-271677980>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT5SXZSfR2bZjL7jh-ZGYFRelg8avj4Mks5rQ-AbgaJpZM4LdbSJ>
> .
>