Patch 1
fossasia/gci16.fossasia.org pull request #867
Opened 2017-01-08 05:57 UTC by Flashguru

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-01-08 07:06 UTC, Abhi2424shek commented
@Flashguru do you know to resolve merge conflicts if yes please resolve them or we will do it for you.

2017-01-08 07:12 UTC, abishekvashok requested changes

2017-01-08 07:12 UTC, Abhi2424shek commented on _data/students.yml
> +  twitter: @flamingmangoe
Please don't include the @ character.

2017-01-09 00:16 UTC, Flashguru commented on _data/students.yml
> +  twitter: @flamingmangoe
I don't know how to resolve merge conflicts but I will remove the @. thanks

2017-01-09 00:28 UTC, robbyoconnor commented
I resolved the conflict.

2017-01-09 00:32 UTC, merged

2017-01-09 00:32 UTC, robbyoconnor commented
@Flashguru in the future title your pull requests better.