credential
fossasia/gci16.fossasia.org pull request #88
Opened 2016-12-02 08:26 UTC by AlexTurning

2016-12-02 09:59 UTC, shubham-padia commented
Please resolve the merge conflicts.

2016-12-02 10:20 UTC, jig08 commented on index.html
>              </div>
@AlexTurning May I know why have you added twice ?

2016-12-02 10:22 UTC, jig08 commented
@AlexTurning 
* Squash all your commits into one and rename it to something meaningful, such as "Adding <-your-name-> in students section"
* Resolve merge conflicts, this [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) might be helpful.

2016-12-02 13:45 UTC, daminisatya requested changes
Requesting changes mentioned by the mentors! Thank you

2016-12-06 05:26 UTC, Abhi2424shek commented
Please don't update index.htmk to add your blog just add it at blogs.yml only and place the picture. :) Happy coding 😉

2016-12-06 07:23 UTC, jig08 commented
Wrt [rules in CONTRIBUTING.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md), closing this.

2016-12-06 07:23 UTC, closed without merging