Update blogs.yml
fossasia/gci16.fossasia.org pull request #909
Opened 2017-01-12 18:09 UTC by tarsdev

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-01-12 18:19 UTC, oanarosca commented
Thanks! Please check the boxes in the description and add your image file - `tdev.jpg` is not part of your commit.

2017-01-12 19:07 UTC, tarsdev commented
I have done it

2017-01-12 20:09 UTC, oanarosca commented
@tarsdev the .jpg file is not present -- look at the `Files changed` tab, you only edited the blogs file. Add the image and commit again.

2017-01-13 01:04 UTC, robbyoconnor requested changes

2017-01-13 01:04 UTC, robbyoconnor commented on _data/blogs.yml
> +  blog_img: tdev.jpg
this does not exist.

2017-01-13 01:05 UTC, robbyoconnor requested changes
see comments. add the image to `images/blogs`

2017-01-15 14:49 UTC, oanarosca commented
Any updates on this?

2017-01-16 03:14 UTC, robbyoconnor commented
Closing due to lack of activity.

2017-01-16 03:14 UTC, closed without merging