Added 3 columns in Social media section in 1 row.
fossasia/gci16.fossasia.org pull request #978
Opened 2017-01-29 08:16 UTC by harshit98

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request
I have added 3 columns in social media section in 1 row. Used a different color for each section. Increased the size of areas to fit well into the design.
Fixes issue no. #924 and #961 
![selection_007](https://cloud.githubusercontent.com/assets/22245418/22402794/1818e6aa-e629-11e6-9772-e838eb19c835.png)
![selection_009](https://cloud.githubusercontent.com/assets/22245418/22402797/1d708dec-e629-11e6-98c2-a4fc179a7309.png)

2017-01-29 08:19 UTC, Abhi2424shek commented
I would resolve the conflicts for you.... Adding WIP since it's a work in progress.

2017-01-30 20:45 UTC, harshit98 commented
Screenshot of the following changes I have made in Social Media sections -
![screenshot from 2017-01-31 02-14-17](https://cloud.githubusercontent.com/assets/22245418/22440861/15548a90-e75b-11e6-94da-99f2e11ffc78.png)

2017-01-31 08:05 UTC, Abhi2424shek commented
@harshit98 i think you got in wrong, just make the sections which were already there smaller don't put it like this.

2017-01-31 09:02 UTC, m1guelpf commented
@harshit98 @Abhi2424shek Adding discussion.
Also requesting @robbyoconnor opinion

2017-01-31 09:23 UTC, robbyoconnor commented
Please link me to your live site please? You didn't read the text beside those checkboxes...

2017-01-31 09:32 UTC, robbyoconnor requested changes
- Use icons and not images 
- if you insist on using the images...Actually be mindful of their names! 

Your file names are absurd. Rename them, or better yet don't even use them at all! Use either glyphicon or font-awesome.

2017-01-31 09:32 UTC, robbyoconnor commented on index.html
> +                        <img src="images/github-logo-200x200.png">
Use a glyphicon/font-awesome icon.

2017-01-31 09:32 UTC, robbyoconnor commented on index.html
> +                            <img src="images/facebook.png">
Use a glyphicon/font-awesome icon.

2017-01-31 09:32 UTC, robbyoconnor commented on index.html
> +                        <img src="images/Google%20Plus%20Logo%20(4).png" alt="google-plus" class="header-image" style="float:center" height=200 width="200">
The file name is absurd. Use a glyphicon/font-awesome icon instead. We load too many images as-is.

2017-01-31 09:33 UTC, robbyoconnor commented
@fossasia/gci16-maintainers -- do not merge this. The file names chosen by @harshit98 are bad, really bad.

2017-01-31 14:03 UTC, harshit98 commented
@robbyoconnor Okay, I'll try to fix it as per your suggestions.

2017-01-31 20:36 UTC, harshit98 commented
Live Link Preview - https://harshit98.github.io/gci16.fossasia.org/

2017-01-31 20:48 UTC, robbyoconnor commented
@harshit98 Here's what you need to do: 

- Clone your fork
- Work locally
- **_DELETE_** The images entirely.

2017-01-31 20:49 UTC, robbyoconnor commented
@harshit98 Here's what you need to do: 

- Clone your fork
- Work locally
- **_DELETE_** The images entirely. 
- Commit and push! 
- ???
- PROFIT1111!111

2017-01-31 20:53 UTC, robbyoconnor requested changes
Looks Better...Now squash.

2017-01-31 20:56 UTC, harshit98 commented
@robbyoconnor okay.

2017-01-31 21:00 UTC, robbyoconnor requested changes
When coding be consistent with style.  See code comments

2017-01-31 21:00 UTC, robbyoconnor commented on index.html
> +    </section><!--End of Social Media section-->
Move comment to next line

2017-01-31 21:07 UTC, robbyoconnor commented
Fix linting issues found by Coala please: https://travis-ci.org/fossasia/gci16.fossasia.org/builds/197093160#L450

2017-01-31 23:39 UTC, robbyoconnor commented
You have got to be kidding me. **_WORK LOCALLY ON YOUR COMPUTER!_**

2017-01-31 23:39 UTC, robbyoconnor commented
Run coala locally: Instructions are here: http://coala.io/#!/home

2017-01-31 23:46 UTC, robbyoconnor commented
The the style violations you are seeing -- look at the surrounding code and how things are done.

2017-02-03 02:36 UTC, robbyoconnor commented
**EDIT THE FILES ON YOUR COMPUTER AND USE MEANINFUL COMMIT MESSAGES!**

2017-02-03 02:36 UTC, robbyoconnor commented
@harshit98  -- **EDIT THE FILES ON YOUR COMPUTER AND USE MEANINFUL COMMIT MESSAGES!**

2017-02-03 02:37 UTC, harshit98 commented
I have edited the file on my computer only. Also, runned the coala locally - the command you gave it worked. And fixed the linting errors.

2017-02-03 02:39 UTC, robbyoconnor commented
Okay then fix your commit messages. They're horrible.

2017-02-03 02:42 UTC, robbyoconnor commented
@fossasia/gci16-maintainers: what's your opinion?

2017-02-03 04:06 UTC, Abhi2424shek commented
Well more work needed:
![screenshot_2017-02-03-09-33-33-226_com android chrome](https://cloud.githubusercontent.com/assets/8947010/22579199/29f77bd8-e9f4-11e6-8de4-c62611b3b7c5.png)


Not responsive design

2017-02-03 10:45 UTC, robbyoconnor requested changes
- [ ] You
 still have responsiveness problems. 

Here's what you need to do to test: narrow your browser window...things should reflow naturally... This doesn't happen here. Narrowing your browser window will simulate what happens on a cell phone.

2017-02-03 13:26 UTC, harshit98 commented
@robbyoconnor I did what you said. I didn't saw any overlapping of sections as per screenshot by @Abhi2424shek

2017-02-03 21:23 UTC, robbyoconnor commented
@harshit98 -- It just plain doesn't look good.

2017-02-03 21:24 UTC, robbyoconnor commented
The +

2017-02-03 21:26 UTC, robbyoconnor commented
here: 

![image](https://cloud.githubusercontent.com/assets/23088/22609037/807279c0-ea2d-11e6-917a-103ba9b82ac8.png)

![image](https://cloud.githubusercontent.com/assets/23088/22609043/843cc4a2-ea2d-11e6-8b95-9acae3b5167d.png)

2017-02-03 21:27 UTC, robbyoconnor commented
No overlapping?

2017-02-04 01:49 UTC, harshit98 commented
@robbyoconnor ok. But now, I'm not doing this. Please close this PR.

2017-02-04 02:32 UTC, robbyoconnor commented
Why are you giving up? Because it's not easy? Consider a better design that works in a way that's responsive for ANY screen size.

2017-02-04 07:12 UTC, Abhi2424shek commented
Dont give up

2017-02-04 07:38 UTC, harshit98 commented
@robbyoconnor any suggestions on responsive design?

2017-02-04 08:40 UTC, robbyoconnor commented
I'm not the best person.. but what you're doing isn't the correct way. Read up on responsive design.

2017-02-05 09:29 UTC, harshit98 commented
So should I keep the design same and just make some tweaks so that the section is responsive for every screen size?

2017-02-05 11:10 UTC, harshit98 commented
Should I remove the flicker slider? It is creating a lot of trouble! and slow time while loading the social-media section. Instead of using the flicker-slider, I'll add the section of flicker with an icon and link, which will be a nice way and easier to load the social-section.

2017-02-05 11:16 UTC, robbyoconnor commented
No. Everything should stay.

2017-02-05 13:03 UTC, harshit98 commented
Live Link Preview - https://harshit98.github.io/gci16.fossasia.org/

2017-02-05 15:44 UTC, m1guelpf commented
![screenshot_2017-02-05-16-43-54](https://cloud.githubusercontent.com/assets/23558090/22627373/56356b36-ebc2-11e6-91e4-e300935df270.png)

2017-02-05 16:38 UTC, ankitrgadiya commented
No offence but TBH this doesn't make sense to me. We're already having fa icons in the footer. This section was supposed to show iframe or something like that using social media api.

2017-02-05 22:14 UTC, robbyoconnor commented
Yeah...I'm with @ankitrgadiya on this..

2017-02-05 22:19 UTC, robbyoconnor commented
@harshit98 -- look at the current implementation and just change the layout using Bootstrap.

2017-02-07 02:39 UTC, harshit98 commented
Sorry did the wrong commits. Close this PR, I'll make a new one.

2017-02-07 02:40 UTC, closed without merging